# Generated by Django 6.0.2 on 2026-09-03 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['project', 'created_at'], name='pages_chatm_project_837da1_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['project', '-created_at'], name='pages_gener_project_64bd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['project', 'is_current'], name='pages_gener_project_511c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-created_at'], name='pages_proje_user_id_0609cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='pages_proje_status_c078f3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['slug'], name='pages_proje_slug_05948e_idx'),
        ),
    ]
