# Generated by Django 6.0.2 on 2026-09-03 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_chatmessage_pages_chatm_project_837da1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPixelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_pixel_id', models.CharField(blank=True, help_text='15–20 digit Meta Pixel ID from Events Manager.', max_length=20)),
                ('meta_access_token', models.CharField(blank=True, help_text='Meta System User access token for CAPI forwarding.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pixel_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pixel Config',
            },
        ),
    ]
