# Generated by Django 6.0.2 on 2026-09-03 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_userpixelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Direct checkout redirect URL (Shopify, Stripe, Razorpay, WhatsApp)', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='enable_lead_capture',
            field=models.BooleanField(default=True, help_text='Enable native COD / inquiry capture drawer on published page'),
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text='e.g. drop.yourbrand.com', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('failed', 'Verification Failed')], default='pending', max_length=30)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domain', to='pages.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'Page View'), ('click', 'CTA Click'), ('lead', 'Lead Submitted')], max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='pages.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'event_type', '-created_at'], name='pages_analy_project_078cd9_idx'), models.Index(fields=['project', 'utm_campaign'], name='pages_analy_project_442c28_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Delivery address for COD orders')),
                ('variant', models.CharField(blank=True, help_text='Selected variant, size, or color', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Lead / Order'), ('contacted', 'Contacted / Confirmed'), ('completed', 'Completed / Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='pages.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='pages_leado_project_0de5d0_idx'), models.Index(fields=['status'], name='pages_leado_status_aafb11_idx')],
            },
        ),
    ]
